/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emppayroll;


import java.awt.Label;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author sachith
 */
public class pnl_user extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form pnl_user
     */
    public pnl_user() {
        initComponents();
        
        //connect to DB
        con = DBconnection.connect();
        
        lbl_LUNn.setText(String.valueOf(Emp.empun).toString());
        imagesett();
        getdetails();
        
        //load table
        tableload();
        
        
        
        
    }
    public void imagesett(){
        
        //img_admin.setVisible(false);
        //img_Sales.setVisible(false);
        //String idd=lbl_LUNn.getText();
        
        
        if(lbl_LUNn.getText().equals("admin")){
            img_admin.setVisible(true);
            img_Sales.setVisible(false);
            jPanel2.setVisible(true);
            jPanel4.setVisible(true);
        }
        
        else{
            img_Sales.setVisible(true);
            img_admin.setVisible(false);
            jPanel2.setVisible(false);
            jPanel4.setVisible(false);
            
        }
        
    }
    public void getdetails(){
        
        try {
            String unamee=lbl_LUNn.getText();
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/emppayrol","root","");
            
            String selectqq="select * from users where username='"+unamee+"'";
            //pst = con.prepareStatement(selectqq);
            //pst.setString(1,lbl_LUNn.getText());
            
            Statement st =con.createStatement();
            rs= st.executeQuery(selectqq);
            
            while(rs.next()){
                String ID=rs.getString("id");
            lbl_LID.setText(ID);
            
            String DIDd=rs.getString("division");
            lbl_LDIV.setText(DIDd);
            }
        
            
            
            
                    
                   
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    public void tableload(){
        try {
            String selectq = "select id,username,password,division from users";
            pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_users.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
            
        } catch (Exception e) {
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_LUNn = new javax.swing.JLabel();
        lbl_LID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_LDIV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_UuserN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_UCreate = new javax.swing.JButton();
        btn_Udelete = new javax.swing.JButton();
        btn_Uupdate = new javax.swing.JButton();
        cmb_UDivi = new javax.swing.JComboBox<>();
        txt_UPw = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        lbl_uid = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        img_admin = new javax.swing.JLabel();
        img_Sales = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_usearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_users = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(746, 595));
        setPreferredSize(new java.awt.Dimension(746, 603));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/user111.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 105));
        jLabel2.setText("User");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 105, 105));
        jLabel7.setText("User:");

        lbl_LUNn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_LUNn.setForeground(new java.awt.Color(105, 105, 105));
        lbl_LUNn.setText("User");

        lbl_LID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_LID.setForeground(new java.awt.Color(105, 105, 105));
        lbl_LID.setText("Id");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 105, 105));
        jLabel10.setText("Id:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(105, 105, 105));
        jLabel11.setText("Division:");

        lbl_LDIV.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_LDIV.setForeground(new java.awt.Color(105, 105, 105));
        lbl_LDIV.setText("Division");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_LDIV)
                    .addComponent(lbl_LID)
                    .addComponent(lbl_LUNn))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_LUNn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_LID))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_LDIV))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 105));
        jLabel13.setText("Username:");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(105, 105, 105));
        jLabel17.setText("Division:");

        txt_UuserN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_UuserN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 105));
        jLabel14.setText("Password:");

        btn_UCreate.setBackground(new java.awt.Color(0, 81, 146));
        btn_UCreate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_UCreate.setForeground(new java.awt.Color(255, 255, 255));
        btn_UCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/create-group-button.png"))); // NOI18N
        btn_UCreate.setText("Create");
        btn_UCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UCreateActionPerformed(evt);
            }
        });

        btn_Udelete.setBackground(new java.awt.Color(0, 81, 146));
        btn_Udelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Udelete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Udelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/cancel-button.png"))); // NOI18N
        btn_Udelete.setText("Delete");
        btn_Udelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UdeleteActionPerformed(evt);
            }
        });

        btn_Uupdate.setBackground(new java.awt.Color(0, 81, 146));
        btn_Uupdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_Uupdate.setForeground(new java.awt.Color(255, 255, 255));
        btn_Uupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/Update button.png"))); // NOI18N
        btn_Uupdate.setText("Update");
        btn_Uupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UupdateActionPerformed(evt);
            }
        });

        cmb_UDivi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Sales" }));

        txt_UPw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(105, 105, 105));
        jLabel15.setText("Id:");

        lbl_uid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_uid.setForeground(new java.awt.Color(105, 105, 105));
        lbl_uid.setText("Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_UCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Udelete)
                                .addGap(14, 14, 14)
                                .addComponent(btn_Uupdate))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(27, 27, 27))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(32, 32, 32)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(45, 45, 45)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(cmb_UDivi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_UPw)
                                    .addComponent(txt_UuserN))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(81, 81, 81)
                        .addComponent(lbl_uid)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_UuserN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_UPw, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_UDivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbl_uid))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_UCreate)
                    .addComponent(btn_Udelete)
                    .addComponent(btn_Uupdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        img_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/admin user.png"))); // NOI18N
        img_admin.setText("jLabel4");
        img_admin.setPreferredSize(new java.awt.Dimension(178, 178));
        jPanel3.add(img_admin);

        img_Sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/user.png"))); // NOI18N
        img_Sales.setText("jLabel4");
        img_Sales.setPreferredSize(new java.awt.Dimension(178, 178));
        jPanel3.add(img_Sales);

        txt_usearch.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_usearch.setToolTipText("Enter your User Name");
        txt_usearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_usearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usearchKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        table_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_users);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usearch, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_usearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UCreateActionPerformed
        String username = txt_UuserN.getText();
        String password = txt_UPw.getText();
        String division= cmb_UDivi.getSelectedItem().toString();
        
        
        
        
        try {
            String insertq="insert into users(username,password,division) values('"+username+"','"+password+"','"+division+"')";
            
            pst = con.prepareStatement(insertq);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved succssfully");
            //load table
            tableload();
            txt_UuserN.setText("");
            txt_UPw.setText("");
            cmb_UDivi.setSelectedIndex(0);
            lbl_uid.setText("id");
            
        } catch (SQLException ex) {
            Logger.getLogger(pnl_user.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            
        
            
            
        
        
    }//GEN-LAST:event_btn_UCreateActionPerformed

    private void btn_UdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UdeleteActionPerformed
        int x = JOptionPane.showConfirmDialog(null,"Do you want to delete this");
        
        if(x==0){
            
            String id = lbl_uid.getText();
            
            try {
                String deleteq="delete from users where id='"+id+"'";
                pst = con.prepareStatement(deleteq);
                pst.execute();
                //load table
                tableload();
                txt_UuserN.setText("");
                txt_UPw.setText("");
                cmb_UDivi.setSelectedIndex(0);
                lbl_uid.setText("id");
                
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btn_UdeleteActionPerformed

    private void table_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_usersMouseClicked
        int r = table_users.getSelectedRow();
        
        String id = table_users.getValueAt(r, 0).toString();
        String uname = table_users.getValueAt(r, 1).toString();
        String passw = table_users.getValueAt(r, 2).toString();
        String div = table_users.getValueAt(r, 3).toString();
        
        txt_UuserN.setText(uname);
        txt_UPw.setText(passw);
        cmb_UDivi.setSelectedItem(div);
        lbl_uid.setText(id);
        
    }//GEN-LAST:event_table_usersMouseClicked

    private void btn_UupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UupdateActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to update");
        
        if(x==0){
            String idd = lbl_uid.getText();
            String uname = txt_UuserN.getText();
            String passw = txt_UPw.getText();
            String div = cmb_UDivi.getSelectedItem().toString();
            
            
            try {
                
                String updateq="update users set username='"+uname+"',password='"+passw+"',division='"+div+"' where id='"+idd+"'";
                pst = con.prepareStatement(updateq);
                pst.execute();
                //load table
                tableload();
                txt_UuserN.setText("");
                txt_UPw.setText("");
                cmb_UDivi.setSelectedIndex(0);
                lbl_uid.setText("id");
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btn_UupdateActionPerformed

    private void txt_usearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usearchKeyPressed
        String name= txt_usearch.getText();
        
        try {
            String selectq="select id,username,password,division from users where username like'%"+name+"%'";
        
        pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_users.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_txt_usearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UCreate;
    private javax.swing.JButton btn_Udelete;
    private javax.swing.JButton btn_Uupdate;
    private javax.swing.JComboBox<String> cmb_UDivi;
    private javax.swing.JLabel img_Sales;
    private javax.swing.JLabel img_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_LDIV;
    private javax.swing.JLabel lbl_LID;
    private javax.swing.JLabel lbl_LUNn;
    private javax.swing.JLabel lbl_uid;
    private javax.swing.JTable table_users;
    private javax.swing.JPasswordField txt_UPw;
    private javax.swing.JTextField txt_UuserN;
    private javax.swing.JTextField txt_usearch;
    // End of variables declaration//GEN-END:variables
}
