/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package emppayroll;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sachith
 */
public class pnl_dball extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /** Creates new form pnl_dball */
    public pnl_dball() {
        initComponents();
        
        //connect to DB
        con = DBconnection.connect();
        loadtables();
    }

    
    public void loadtables(){
        try {
            String selectq = "select * from users";
            pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_user.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            String selectq2 = "select * from employee";
            pst = con.prepareStatement(selectq2);
            rs=pst.executeQuery();
            
            table_emp.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            String selectq3 = "select * from deductions";
            pst = con.prepareStatement(selectq3);
            rs=pst.executeQuery();
            
            table_deduct.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            String selectq4 = "select * from allowance";
            pst = con.prepareStatement(selectq4);
            rs=pst.executeQuery();
            
            table_allow.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
            
                   
        } catch (Exception e) {
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_emp = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_deduct = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txt_deduct = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_allow = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_allow = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(746, 603));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 105));
        jLabel2.setText("Database");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/databasegrayy.png"))); // NOI18N

        txt_user.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_user.setToolTipText("Enter your username");
        txt_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_userKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 105));
        jLabel13.setText("users");

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_user);

        table_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_emp);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 105, 105));
        jLabel14.setText("employee");

        txt_emp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_emp.setToolTipText("Enter employee ID");
        txt_emp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_emp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_empKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_empKeyReleased(evt);
            }
        });

        table_deduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_deduct);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(105, 105, 105));
        jLabel15.setText("deductions");

        txt_deduct.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_deduct.setToolTipText("Enter employee ID");
        txt_deduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_deduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_deductKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(105, 105, 105));
        jLabel16.setText("allowance");

        txt_allow.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_allow.setToolTipText("Enter employee ID");
        txt_allow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_allow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_allowKeyReleased(evt);
            }
        });

        table_allow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_allow);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(txt_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_deduct, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(txt_allow, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_deduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(txt_allow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyReleased
        String name= txt_user.getText();
        
        try {
            String selectq="select * from users where username like'%"+name+"%'";
        
        pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_user.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_txt_userKeyReleased

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
       /* String name= txt_user.getText();
        
        try {
            String selectq="select * from users where username like'%"+name+"%'";
        
        pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_user.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_empKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_empKeyPressed
        /*String emp= txt_emp.getText();
        
        try {
            String selectq="select * from employee where empid='"+emp+"'";
        
        pst = con.prepareStatement(selectq);
            rs=pst.executeQuery();
            
            table_emp.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_txt_empKeyPressed

    private void txt_empKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_empKeyReleased
       String emp= txt_emp.getText();
        if(emp.equals("")){
            
            
           try {
            String selectq1="select * from employee";
        
        pst = con.prepareStatement(selectq1);
            rs=pst.executeQuery();
            
            table_emp.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        }
        else{
        
            try {
            String selectq2="select * from employee where empid='"+emp+"'";
        
        pst = con.prepareStatement(selectq2);
            rs=pst.executeQuery();
            
            table_emp.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
        
        
        
        
        
    }//GEN-LAST:event_txt_empKeyReleased

    private void txt_deductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_deductKeyReleased
        String emp= txt_deduct.getText();
        if(emp.equals("")){
            
            
           try {
            String selectq1="select * from deductions";
        
        pst = con.prepareStatement(selectq1);
            rs=pst.executeQuery();
            
            table_deduct.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            
            
        }
        }
        else{
        
            try {
            String selectq2="select * from deductions where emp_id='"+emp+"'";
        
        pst = con.prepareStatement(selectq2);
            rs=pst.executeQuery();
            
            table_deduct.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    }//GEN-LAST:event_txt_deductKeyReleased

    private void txt_allowKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_allowKeyReleased
        String emp= txt_allow.getText();
        if(emp.equals("")){
            
            
           try {
            String selectq1="select * from allowance";
        
        pst = con.prepareStatement(selectq1);
            rs=pst.executeQuery();
            
            table_allow.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            
            
        }
        }
        else{
        
            try {
            String selectq2="select * from allowance where emp_id='"+emp+"'";
        
        pst = con.prepareStatement(selectq2);
            rs=pst.executeQuery();
            
            table_allow.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    }//GEN-LAST:event_txt_allowKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_allow;
    private javax.swing.JTable table_deduct;
    private javax.swing.JTable table_emp;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_allow;
    private javax.swing.JTextField txt_deduct;
    private javax.swing.JTextField txt_emp;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

}
