/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emppayroll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author sachith
 */
public class pnl_search extends javax.swing.JPanel {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form pnl_search
     */
    public pnl_search() {
        initComponents();
        
        //connect to DB
        con = DBconnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        r_smale = new javax.swing.JRadioButton();
        r_sfemale = new javax.swing.JRadioButton();
        txt_sdept = new javax.swing.JTextField();
        txt_sdesignation = new javax.swing.JTextField();
        txt_sbsal = new javax.swing.JTextField();
        txt_sjobt = new javax.swing.JTextField();
        lblgen = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmb_sstatus = new javax.swing.JComboBox<>();
        dtp_sdateh = new com.toedter.calendar.JDateChooser();
        txt_semail = new javax.swing.JTextField();
        txt_scontact = new javax.swing.JTextField();
        txt_sadd1 = new javax.swing.JTextField();
        txt_sadd2 = new javax.swing.JTextField();
        txt_sapt = new javax.swing.JTextField();
        txt_spostc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dtp_sdob = new com.toedter.calendar.JDateChooser();
        txt_ssurn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sfirstn = new javax.swing.JTextField();
        txt_sid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_supdate = new javax.swing.JButton();
        btn_sclear = new javax.swing.JButton();
        btn_sdelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(746, 595));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Employee Id:");

        txt_search.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/magnifier.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 105, 105));
        jLabel2.setText("Search");

        r_smale.setText("Male");
        r_smale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_smaleActionPerformed(evt);
            }
        });

        r_sfemale.setText("Female");
        r_sfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_sfemaleActionPerformed(evt);
            }
        });

        txt_sdept.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sdept.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_sdesignation.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sdesignation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_sbsal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sbsal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_sbsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sbsalKeyTyped(evt);
            }
        });

        txt_sjobt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sjobt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        lblgen.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblgen.setText("Gender:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Department:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Email:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Designation:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Contact:");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Status:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Address Line 1:");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Date Hired:");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Address Line 2:");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Basic Salary:");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Apt/House No:");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Job Title:");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Post Code:");

        cmb_sstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Part Time", "Temporary", "On Call" }));
        cmb_sstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 105)));

        txt_semail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_semail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_scontact.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_scontact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));
        txt_scontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_scontactKeyTyped(evt);
            }
        });

        txt_sadd1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sadd1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_sadd2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sadd2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_sapt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sapt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_spostc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_spostc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Date of Birth:");

        txt_ssurn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_ssurn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Surname:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("First name:");

        txt_sfirstn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sfirstn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        txt_sid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_sid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 105, 105), 1, true));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Employee Id:");

        btn_supdate.setBackground(new java.awt.Color(0, 81, 146));
        btn_supdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_supdate.setForeground(new java.awt.Color(255, 255, 255));
        btn_supdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/Update button.png"))); // NOI18N
        btn_supdate.setText("Update");
        btn_supdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supdateActionPerformed(evt);
            }
        });

        btn_sclear.setBackground(new java.awt.Color(0, 81, 146));
        btn_sclear.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_sclear.setForeground(new java.awt.Color(255, 255, 255));
        btn_sclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/clearA.png"))); // NOI18N
        btn_sclear.setText("Clear");
        btn_sclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sclearActionPerformed(evt);
            }
        });

        btn_sdelete.setBackground(new java.awt.Color(0, 81, 146));
        btn_sdelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_sdelete.setForeground(new java.awt.Color(255, 255, 255));
        btn_sdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/cancel-button.png"))); // NOI18N
        btn_sdelete.setText("Delete");
        btn_sdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sdeleteActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emppayroll/user.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_spostc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sapt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(lblgen)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_scontact)
                            .addComponent(txt_semail)
                            .addComponent(txt_ssurn)
                            .addComponent(txt_sfirstn)
                            .addComponent(txt_sid)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r_smale)
                                .addGap(18, 18, 18)
                                .addComponent(r_sfemale))
                            .addComponent(dtp_sdob, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sjobt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sbsal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sdept, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_sstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtp_sdateh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_supdate)
                .addGap(36, 36, 36)
                .addComponent(btn_sdelete)
                .addGap(42, 42, 42)
                .addComponent(btn_sclear)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_sfirstn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_ssurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dtp_sdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgen)
                    .addComponent(r_smale)
                    .addComponent(r_sfemale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_semail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_scontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_sadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_sadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_sapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_spostc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_sdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_sdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cmb_sstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(dtp_sdateh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_sbsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_sjobt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sclear)
                    .addComponent(btn_supdate)
                    .addComponent(btn_sdelete))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try {
            
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/emppayrol","root","");
            String selectq ="select * from employee where empid=? ";
            pst=con.prepareStatement(selectq);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            while(rs.next()){
                
                
               
                txt_sid.setText(rs.getString("empid"));
                txt_sfirstn.setText(rs.getString("first_name"));
                txt_ssurn.setText(rs.getString("surname"));
                txt_scontact.setText(rs.getString("contact"));
                
                txt_semail.setText(rs.getString("email"));
                txt_sadd1.setText(rs.getString("address1"));
                txt_sdept.setText(rs.getString("department"));
                
                txt_sbsal.setText(rs.getString("basic_sal"));
                txt_sadd2.setText(rs.getString("address2"));
                txt_spostc.setText(rs.getString("post_code"));
                txt_sdesignation.setText(rs.getString("designation"));
                txt_sjobt.setText(rs.getString("job_title"));
                txt_sapt.setText(rs.getString("apt"));
                
                
                String genderr=null;
                      genderr=rs.getString("gender");
                
                //lblgen.setText(genderr);
                if(genderr.equals("Male")){
                    r_smale.setSelected(true);
                    r_sfemale.setSelected(false);
                    
                }
                
                if(genderr.equals("Female")) {
                    
                    r_sfemale.setSelected(true);
                    r_smale.setSelected(false);
                }
                
                String date=rs.getString("dob");
                ((JTextField)dtp_sdob.getDateEditor().getUiComponent()).setText(date);
                
                String datehired=rs.getString("date_hired");
                ((JTextField)dtp_sdateh.getDateEditor().getUiComponent()).setText(datehired);
                
                
                
                String status=null;
                       status= rs.getString("status");   
                
                if(status.equals("Full Time")){
                    
                    cmb_sstatus.setSelectedIndex(0);
                }
                
                else if(status.equals("Part Time")){
                    
                    cmb_sstatus.setSelectedIndex(1);
                }
                
                else if(status.equals("Temporary")){
                    
                    cmb_sstatus.setSelectedIndex(2);
                }
                
                else if(status.equals("On Call")){
                    
                    cmb_sstatus.setSelectedIndex(3);
                }
           
            }
           
            
        } catch (Exception e) {
            
            //JOptionPane.showMessageDialog(null, "Missing Data");
        }
        
        finally{
            try {
                con.close();
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void r_smaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_smaleActionPerformed
        gender ="Male";
        r_sfemale.setSelected(false);
        r_smale.setSelected(true);
    }//GEN-LAST:event_r_smaleActionPerformed

    private void r_sfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_sfemaleActionPerformed
        gender ="Female";
        r_sfemale.setSelected(true);
        r_smale.setSelected(false);
    }//GEN-LAST:event_r_sfemaleActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        /*try {
            
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/emppayrol","root","");
            String selectq ="select * from employee where empid=? ";
            pst=con.prepareStatement(selectq);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                
                //String eid =rs.getString("empid");
                txt_sid.setText(rs.getString("empid"));
            }
            
            
        } catch (Exception e) {
            
            //JOptionPane.showMessageDialog(null, "Missing Data");
        }
        
        finally{
            try {
                con.close();
                pst.close();
                rs.close();
            } catch (Exception e) {
            }
        }*/
    }//GEN-LAST:event_txt_searchKeyPressed

    private void btn_sclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sclearActionPerformed
        txt_sid.setText("");
        txt_sfirstn.setText("");
        txt_ssurn.setText("");
        txt_scontact.setText("");
        dtp_sdob.setCalendar(null);
        txt_semail.setText("");
        txt_sadd1.setText("");
        txt_sdept.setText("");
        cmb_sstatus.setSelectedIndex(0);
        txt_sbsal.setText("");
        txt_sadd2.setText("");
        txt_spostc.setText("");
        txt_sdesignation.setText("");
        txt_sjobt.setText("");
        txt_sapt.setText("");
        dtp_sdateh.setCalendar(null);
        r_smale.setSelected(false);
        r_sfemale.setSelected(false);
        txt_search.setText("");
    }//GEN-LAST:event_btn_sclearActionPerformed

    private void btn_supdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supdateActionPerformed
        
        
        
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/emppayrol","root","");
            
        String id =txt_sid.getText();
        String fname =txt_sfirstn.getText();
        String surname =txt_ssurn.getText();
        String contact =txt_scontact.getText();
        String dofb = ((JTextField)dtp_sdob.getDateEditor().getUiComponent()).getText();
        String doj = ((JTextField)dtp_sdateh.getDateEditor().getUiComponent()).getText();      
        String email =txt_semail.getText();
        String add1 =txt_sadd1.getText();
        String dept =txt_sdept.getText();  
        String statuss =cmb_sstatus.getSelectedItem().toString();  
        String bsalary =txt_sbsal.getText();
        String add2 =txt_sadd2.getText();
        String pc =txt_spostc.getText();
        String design =txt_sdesignation.getText();
        String jobtitle =txt_sjobt.getText();
        String apt =txt_sapt.getText();
        String genderrr=gender;
        
        if(r_smale.isSelected()){
            genderrr="Male";      
        }
        
        else if(r_sfemale.isSelected()){
            genderrr="Female";
        }
        
        
        String updateq= "update employee set empid='"+id+"',first_name='"+fname+"',surname='"+surname+"',dob='"+dofb+"',gender='"+genderrr+"',email='"+email+"',contact='"+contact+"',address1='"+add1+"',address2='"+add2+"',apt='"+apt+"',post_code='"+pc+"',department='"+dept+"',designation='"+design+"',status='"+statuss+"',date_hired='"+doj+"',basic_sal='"+bsalary+"',job_title='"+jobtitle+"' where empid='"+id+"'";
        
        Statement st=con.createStatement();
        st.executeUpdate(updateq);
        JOptionPane.showMessageDialog(null, "Record Updated");
        
        txt_sid.setText("");
        txt_sfirstn.setText("");
        txt_ssurn.setText("");
        txt_scontact.setText("");
        dtp_sdob.setCalendar(null);
        txt_semail.setText("");
        txt_sadd1.setText("");
        txt_sdept.setText("");
        cmb_sstatus.setSelectedIndex(0);
        txt_sbsal.setText("");
        txt_sadd2.setText("");
        txt_spostc.setText("");
        txt_sdesignation.setText("");
        txt_sjobt.setText("");
        txt_sapt.setText("");
        dtp_sdateh.setCalendar(null);
        r_smale.setSelected(false);
        r_sfemale.setSelected(false);
        txt_search.setText("");
        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_btn_supdateActionPerformed

    private void btn_sdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sdeleteActionPerformed
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/emppayrol","root","");
            String idd =txt_sid.getText();
            String deleteq="delete from employee where empid='"+idd+"'";
            
            Statement st=con.createStatement();
            st.executeUpdate(deleteq);
            //pst=con.prepareStatement(deleteq);
            //pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted");
            
            txt_sid.setText("");
        txt_sfirstn.setText("");
        txt_ssurn.setText("");
        txt_scontact.setText("");
        dtp_sdob.setCalendar(null);
        txt_semail.setText("");
        txt_sadd1.setText("");
        txt_sdept.setText("");
        cmb_sstatus.setSelectedIndex(0);
        txt_sbsal.setText("");
        txt_sadd2.setText("");
        txt_spostc.setText("");
        txt_sdesignation.setText("");
        txt_sjobt.setText("");
        txt_sapt.setText("");
        dtp_sdateh.setCalendar(null);
        r_smale.setSelected(false);
        r_sfemale.setSelected(false);
        txt_search.setText("");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_sdeleteActionPerformed

    private void txt_scontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_scontactKeyTyped
        char c=evt.getKeyChar();

String text=txt_scontact.getText();
       if (c == 43 && text.indexOf('+') != -1)
            {
                evt.consume();
            }
       if (!Character.isDigit(c) && c != 8 && c != 43)
            {
                evt.consume();
            }
    }//GEN-LAST:event_txt_scontactKeyTyped

    private void txt_sbsalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sbsalKeyTyped
        char ch = evt.getKeyChar();
       
       String amount=txt_sbsal.getText();

            if (ch == 46 && amount.indexOf('.') != -1)
            {
                evt.consume();
            }

            if (!Character.isDigit(ch) && ch != 8 && ch != 46)
            {
                evt.consume();
            }
    }//GEN-LAST:event_txt_sbsalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sclear;
    private javax.swing.JButton btn_sdelete;
    private javax.swing.JButton btn_supdate;
    private javax.swing.JComboBox<String> cmb_sstatus;
    private com.toedter.calendar.JDateChooser dtp_sdateh;
    private com.toedter.calendar.JDateChooser dtp_sdob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblgen;
    private javax.swing.JRadioButton r_sfemale;
    private javax.swing.JRadioButton r_smale;
    private javax.swing.JTextField txt_sadd1;
    private javax.swing.JTextField txt_sadd2;
    private javax.swing.JTextField txt_sapt;
    private javax.swing.JTextField txt_sbsal;
    private javax.swing.JTextField txt_scontact;
    private javax.swing.JTextField txt_sdept;
    private javax.swing.JTextField txt_sdesignation;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_semail;
    private javax.swing.JTextField txt_sfirstn;
    private javax.swing.JTextField txt_sid;
    private javax.swing.JTextField txt_sjobt;
    private javax.swing.JTextField txt_spostc;
    private javax.swing.JTextField txt_ssurn;
    // End of variables declaration//GEN-END:variables
private String gender;
}
